<?php
/**
 * @author Convert Team
 * @copyright Copyright (c) 2018 Convert (http://www.convert.no/)
 */

/** @var Porterbuddy\Porterbuddy\Block\Availability $block */
$helper = $block->getHelper();
?>
<script type="text/x-magento-init">
    {
        "#porterbuddy-widget": {
            "porterbuddyAvailabilityWidget": {
                "getAvailabilityURL": "<?= $block->getUrl('porterbuddy/delivery/availability') ?>",
                "availabilityText": <?= json_encode($helper->getAvailabilityTemplate()) ?>,
                "textClickToSee": <?= json_encode($helper->getAvailabilityTextClickToSee()) ?>,
                "textDeliveryUnavailableTemplate": <?= json_encode($helper->getAvailabilityTextPostcodeError()) ?>,
                "publicKey": <?= json_encode($helper->getPublicKey()) ?>,
                "apiMode": "<?= $helper->getApiMode() ?>",
            }
        }
    }
</script>
